[project]
name = "test"
version = "0.1.0"
description = "Add a short description here"
authors = ["Shenghao Zhou <shzhou@udel.edu>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
config="echo \"Config Project: $SRC_DIR\" && cmake -B $BUILD_DIR -S $SRC_DIR -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_COLOR_DIAGNOSTICS=1 -GNinja"
build="echo \"Build Project: $BUILD_DIR\" && cmake --build $BUILD_DIR -j"
[dependencies]
