[project]
name = "test"
version = "0.1.0"
description = "Add a short description here"
authors = ["Shenghao Zhou <shzhou@udel.edu>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
config="cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_COLOR_DIAGNOSTICS=1 -GNinja"
build="cmake --build build -j"
[dependencies]
